INSERT INTO SERVICE (service_id, name, fee) VALUES (1, 'Save $1 to Account', -1);
INSERT INTO SERVICE (service_id, name, fee) VALUES (2, 'Save $5 to Account', -5);
INSERT INTO SERVICE (service_id, name, fee) VALUES (3, 'Save $10 to Account', -10);
INSERT INTO SERVICE (service_id, name, fee) VALUES (4, 'Save $20 to Account', -20);
INSERT INTO SERVICE (service_id, name, fee) VALUES (5, 'Colonoscopy', 132.22);
INSERT INTO SERVICE (service_id, name, fee) VALUES (6, 'Massage', 75.12);
INSERT INTO SERVICE (service_id, name, fee) VALUES (7, 'Foot Massage', 32.5);
INSERT INTO SERVICE (service_id, name, fee) VALUES (8, 'Liposuction', 3374.22);
INSERT INTO SERVICE (service_id, name, fee) VALUES (9, 'Tool Removal', 175);
INSERT INTO SERVICE (service_id, name, fee) VALUES (10, 'Counseling Session', 55);
INSERT INTO SERVICE (service_id, name, fee) VALUES (11, 'Cocoa Rehabilitation Retreat', 1950.43);
INSERT INTO SERVICE (service_id, name, fee) VALUES (12, 'Diet Consultation', 123.05);
INSERT INTO SERVICE (service_id, name, fee) VALUES (13, 'Vomiting Session', 22.31);
INSERT INTO SERVICE (service_id, name, fee) VALUES (14, 'Skin Graft', 453);
INSERT INTO SERVICE (service_id, name, fee) VALUES (15, 'Molar Scrape', 50);
INSERT INTO SERVICE (service_id, name, fee) VALUES (16, 'Buffet', 7.99);
INSERT INTO SERVICE (service_id, name, fee) VALUES (17, 'Chocolate Scent Therapy', 66.34);
INSERT INTO SERVICE (service_id, name, fee) VALUES (18, 'Crunch Chocolate Bar Destruction Session', 5.99);
INSERT INTO SERVICE (service_id, name, fee) VALUES (19, 'Lobotomy', 763.88);
INSERT INTO SERVICE (service_id, name, fee) VALUES (20, 'Transdermal Implant', 40);
INSERT INTO SERVICE (service_id, name, fee) VALUES (21, 'Nipple Splitting', 73.47);
